version: "3"

services:
  db_node_domain:
    image: mysql:5.7
    container_name: db_server
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: mywordpress
      MYSQL_ROOT_PASSWORD: coffee
      MYSQL_USER_HOST: "%"
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db_node_domain
    image: wordpress:latest
    container_name: wp_web
    ports:
      - "8080:80"
    expose:
      - 80
    environment:
      WORDPRESS_DB_HOST: db_node_domain:3306
      WORDPRESS_DB_NAME: mywordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWD: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

volumes:
  db_data:

