#!/bin/bash
sudo docker-compose down
sudo docker volume ls
sudo docker volume rm $(sudo docker volume ls -q)
sudo docker network ls
sudo docker prune
sudo docker network ls
sudo docker-compose up -d
sudo docker-compose ps
sudo docker-compose logs
sudo docker exec -it db_server /bin/bash
