#!/bin/bash
set -x
# make user that user is in the docker group
grep -q '^docker:.*user' /etc/group || sudo usermod -aG docker user
if [ "$(id -gn)" != "docker" ]
then
    # re-exec the shell script so we are running in the docker group
    exec sg docker "$0 $*"
fi
docker build -t ubuntu-2204-bash-user .
sudo docker run -it -u "1000:1000" --name ubuntu-2204-bash-user --rm ubuntu-2204-bash-user
