version: "3"
services:
  my_macvlan:
    image: alpine
    stdin_open: true
    tty: true
    command: /bin/sh
    networks:
      - eth0
      - port0
      - port1
networks:
  eth0:
    driver: macvlan
    driver_opts:
      com.docker.network.bridge.name: eth0
  port0:
    driver: macvlan
  port1:
    driver: macvlan
